/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.*;
import javax.swing.*;  
import javax.swing.table.*;  
import Users.User;
import Serialization.Serializer;
/**
 *
 * @author Bentsi
 */
public class PrintPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrintPanel
     */
    public PrintPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_Num", "ID", "Name", "Mail", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsers.setColumnSelectionAllowed(true);
        tableUsers.setEnabled(false);
        tableUsers.setRowHeight(20);
        jScrollPane1.setViewportView(tableUsers);
        tableUsers.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClickClose(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OnClickClose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnClickClose
        GUIHandler.setLayoutVisibility(GUIHandler.getMainframe(), GUIHandler.getPrintframe());
    }//GEN-LAST:event_OnClickClose

    public void initTable()
    {
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.CENTER);
        
        DefaultTableModel model = (DefaultTableModel) tableUsers.getModel();

        Set<User> userset = Serializer.deserialzeUserSet();;
        
        try{
            userset.isEmpty();
        
        }catch(NullPointerException ex){
            ex.toString();
            return;
        }
        
        int usernumber = 0;
        int row = 0;
        int col;
        
        for(Object obj : userset)
        {
            col = 0;
            
            model.addRow(new Object[]{});
            tableUsers.getModel().setValueAt(++usernumber, row, col++);
            tableUsers.getModel().setValueAt(((User)obj).getID(), row, col++);
            tableUsers.getModel().setValueAt(((User)obj).getUsername(), row, col++);
            tableUsers.getModel().setValueAt(((User)obj).getMail(), row, col++);
            tableUsers.getModel().setValueAt(((User)obj).getPhone(), row, col++);
            
            row++;
        }
        
        for(int c = 0 ; c < tableUsers.getColumnCount() ; c++)
            tableUsers.getColumnModel().getColumn(c).setCellRenderer(dtcr);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables
}
